// SPDX-License-Identifier: GPL-3.0-only
#include "oni/command_bridge.h"
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <thread>
using namespace std::chrono_literals;
static int checks=0;
static void check(bool value,const char *what){++checks;if(!value)throw std::runtime_error(what);}
static std::string text(const std::filesystem::path&p){std::ifstream f(p);return {std::istreambuf_iterator<char>(f),{}};}
template<class F> static bool wait(F fn){for(int n=0;n<120;++n){if(fn())return true;std::this_thread::sleep_for(25ms);}return false;}
static std::string wire(std::string id=std::string(32,'a')){return "protocol=1\nid="+id+"\ninstance="+std::string(32,'b')+"\naction=record\npreset=lag\nactor=Owner\nrole=operator\nissued_ms=1000\nexpires_ms=121000\nexpected_session=0\n";}
int main(int argc,char **argv){
    // Also supports cross-language protocol fixtures generated by the Python agent.
    if(argc==2){std::string err;auto cmd=oni::parseRemote(text(argv[1]),err);if(!cmd){std::cerr<<err;return 2;}std::cout<<cmd->action<<":"<<cmd->actor;return 0;}
    const auto root=std::filesystem::temp_directory_path()/("oni-bridge-test-"+std::to_string(std::chrono::steady_clock::now().time_since_epoch().count()));
    try{
        std::string error;auto c=oni::parseRemote(wire(),error);check(bool(c),"valid wire");
        check(c->actor=="Owner"&&c->action=="record","wire values");
        check(!oni::parseRemote(wire()+"protocol=1\n",error),"duplicate rejected");
        check(!oni::parseRemote(wire()+"unknown=yes\n",error),"unknown rejected");
        check(!oni::parseRemote(std::string(4097,'x'),error),"oversize rejected");
        check(!oni::parseRemote("",error),"empty rejected");
        check(!oni::bridgeId(std::string(32,'G')),"nonhex rejected");
        check(!oni::bridgeActor("admin\nrole=manager"),"actor injection rejected");
        check(!oni::bridgeAction("stop-server"),"arbitrary console action rejected");
        auto modified=wire();modified.replace(modified.find("1000\n"),4,"9223372036854775808");check(!oni::parseRemote(modified,error),"overflow rejected");
        check(oni::remoteRejection(*c,std::string(32,'b'),1001,true,false).empty(),"operator may record");
        check(!oni::remoteRejection(*c,std::string(32,'b'),1001,false,false).empty(),"local controls gate");
        check(!oni::remoteRejection(*c,std::string(32,'c'),1001,true,true).empty(),"old boot rejected");
        check(!oni::remoteRejection(*c,std::string(32,'b'),121000,true,true).empty(),"expired rejected");
        c->preset="memory";check(!oni::remoteRejection(*c,std::string(32,'b'),1001,true,true).empty(),"operator memory rejected");
        c->role="manager";check(!oni::remoteRejection(*c,std::string(32,'b'),1001,true,false).empty(),"local management gate");
        check(oni::remoteRejection(*c,std::string(32,'b'),1001,true,true).empty(),"manager memory allowed");
        {
            oni::CommandBridge bridge(root);
            check(wait([&]{return std::filesystem::is_directory(root/"inbox");}),"worker initialized");
            auto path=root/"inbox"/(std::string(32,'a')+".cmd");{std::ofstream f(path);f<<wire();}
            std::optional<oni::RemoteCommand> command;
            check(wait([&]{command=bridge.pop();return command.has_value();}),"disk request claimed");
            check(std::filesystem::exists(root/"claimed"/path.filename()),"durable claim exists");
            bridge.acknowledge(command->id,"applied","test completed",123);
            const auto receipt=root/"outbox"/(command->id+".json");
            check(wait([&]{return std::filesystem::exists(receipt);}),"receipt written");
            check(text(receipt).find("\"session\":123")!=std::string::npos,"receipt session");
            bridge.acknowledge(command->id,"error","must not replace");std::this_thread::sleep_for(300ms);
            check(text(receipt).find("must not replace")==std::string::npos,"terminal receipt immutable");
            {std::ofstream f(path);f<<wire();}std::this_thread::sleep_for(400ms);
            check(!bridge.pop(),"duplicate never executes");
            const auto bad=root/"inbox"/(std::string(32,'d')+".cmd");{std::ofstream f(bad);f<<wire();}
            check(wait([&]{return std::filesystem::exists(root/"outbox"/(std::string(32,'d')+".json"));}),"identity mismatch has receipt");
            check(bridge.takeError().empty(),"no worker error");bridge.stop();
        }
        {std::ofstream f(root/"claimed"/(std::string(32,'e')+".cmd"));f<<wire(std::string(32,'e'));}
        {
            oni::CommandBridge bridge(root);const auto receipt=root/"outbox"/(std::string(32,'e')+".json");
            check(wait([&]{return std::filesystem::exists(receipt);}),"interrupted claim recovered");
            check(text(receipt).find("indeterminate")!=std::string::npos,"interrupted action not falsely confirmed");
            check(!bridge.pop(),"interrupted action not replayed");
        }
        std::filesystem::remove_all(root);std::cout<<checks<<" bridge checks passed\n";return 0;
    }catch(const std::exception&e){std::filesystem::remove_all(root);std::cerr<<e.what()<<"\n";return 1;}
}
